language: ruby
rvm:
- 2.1.3
env:
  global:
    secure: DPmSqe2gHlPj/rEJWftjI1nyCBCV6yylgFPeAtgnjY5cstLCiyigOjkGvY9K/JJ48BDTz9/oyYSMl7aeQ9J4rGN2yQP9yQ4ZUVbG4bAKyK93+dPS79Aho5F+L3G1cbYFg4O8NTpXDv28X3WMYAky0k2zj20FQWL3+eI2Kl+I66A=
deploy:
  provider: rubygems
  gem: factor-connector-heroku
  api_key:
    secure: mMY5ZBtkbojnbXBLCnMpvdokLoJU+RbeafrQ3CZpOGXK4+mg8hoY79kdNIYNImF4bhOh3G0Ol0ByCsBGcciX1hknWLyrv8ZNNxlhoDLgTozcTIi8Zyd1SkRD360LUxGn5cDOgX+7o226zh6p2B742dVcgIf8Y469cGxT855DpBg=
  on:
    tags: true
    all_branches: true
